CCFLAGS=/nologo /MD /Ot /fp:precise /W3 /Gd /D_CRT_SECURE_NO_WARNINGS
LINKFLAGS=/nologo /subsystem:console
LINK=link

all: demo.exe demo2.exe

demo.exe: demo.obj console.obj
	$(LINK) $(LINKFLAGS) /out:demo.exe demo.obj console.obj kernel32.lib

demo2.exe: demo2.obj console.obj
	$(LINK) $(LINKFLAGS) /out:demo2.exe demo2.obj console.obj kernel32.lib

.c.obj:
	$(CC) /c /TC $(CCFLAGS) $<

.cpp.obj:
	$(CC) /c $(CCFLAGS) $<

clean:
	-@del *.obj *.exe *.res *.dll *.lib *.map *.pdb
